# Generated by Django 4.1.7 on 2023-03-04 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_rename_type_album_genre_remove_album_track_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songwriter',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор записи по стандарту UUID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Дата последнего изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(null=True, verbose_name='Год выхода альбома'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track', to='tracks.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='album',
            name='songwriter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album', to='tracks.songwriter', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='track',
            name='songwriter',
            field=models.ManyToManyField(related_name='tracks', to='tracks.songwriter', verbose_name='Исполнитель'),
        ),
    ]
