# Generated by Django 4.1.7 on 2023-03-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_songwriter_alter_album_year_alter_track_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songwriter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='tracks.songwriter', verbose_name='Исполнитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track', to='tracks.album', verbose_name='Альбом'),
        ),
    ]
