# Generated by Django 4.1.7 on 2023-03-07 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_alter_album_songwriter_alter_track_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выхода альбома'),
        ),
    ]
