# Generated by Django 4.1.7 on 2023-03-07 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_alter_album_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выхода альбома'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='year',
        ),
        migrations.AddField(
            model_name='track',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выхода трека'),
        ),
    ]
